# Generated by Django 5.1.1 on 2024-10-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0004_alter_guest_email_alter_guest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_text', models.CharField(max_length=100)),
                ('date_shared', models.DateField()),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='guests.guest')),
            ],
        ),
    ]
