# Generated by Django 5.1.1 on 2024-10-09 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memories',
            options={'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
        migrations.AlterField(
            model_name='memories',
            name='date_shared',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
