# Generated by Django 5.1.1 on 2024-10-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_email_alter_guest_phone'),
        ('memories', '0002_alter_memories_options_alter_memories_date_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='guests.guest'),
        ),
    ]
