# Generated by Django 5.1.1 on 2024-10-10 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_alter_memories_options_alter_memories_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='date_shared',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
