# Generated by Django 5.1.1 on 2024-10-10 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_alter_memories_date_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='date_shared',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
