# Generated by Django 5.1.1 on 2024-10-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0004_alter_guest_email_alter_guest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_selection', models.CharField(choices=[('ENG', 'England'), ('AUS', 'Australia'), ('BOTH', 'Both')], max_length=4)),
                ('is_attending', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='guests.guest')),
            ],
        ),
    ]
