# Generated by Django 5.1.1 on 2024-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='wedding_selection',
            field=models.CharField(choices=[('ENG', 'England'), ('AUS', 'Australia'), ('BOTH', 'Both')], max_length=10),
        ),
    ]
