# Generated by Django 5.1.1 on 2024-10-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_email_alter_guest_phone'),
        ('rsvp', '0002_alter_rsvp_wedding_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_response', to='guests.guest'),
        ),
    ]
