# Generated by Django 5.1.1 on 2024-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=60)),
                ('dietary_restrictions', models.FloatField()),
            ],
        ),
    ]
