# Generated by Django 5.1.1 on 2024-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='specific_dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('VGN', 'Vegan'), ('GF', 'Gluten-Free'), ('NUT', 'Nut-Free'), ('LAC', 'Lactose-Free'), ('SPE', 'Specific')], max_length=3),
        ),
    ]
