# Generated by Django 5.1.1 on 2024-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_specific_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('VEG', 'Vegetarian'), ('VGN', 'Vegan'), ('GF', 'Gluten-Free'), ('NUT', 'Nut-Free'), ('LAC', 'Lactose-Free'), ('SPE', 'Specific')], max_length=3),
        ),
    ]
